# Generated by Django 5.1.4 on 2025-04-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_conversationrating_rating_clinical_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clinical_record',
            name='Fasting',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinical_record',
            name='cholestrol_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinical_record',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinical_record',
            name='removed_teeth',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clinical_record',
            name='weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='static_clinical_data',
            name='alcoholic',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='static_clinical_data',
            name='astheme',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='static_clinical_data',
            name='covid_19',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='static_clinical_data',
            name='e_cigarette',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='static_clinical_data',
            name='hypertension_medicales',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='static_clinical_data',
            name='physical_activity',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='static_clinical_data',
            name='prevouis_stroke',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='static_clinical_data',
            name='pulmonary_disease',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='static_clinical_data',
            name='walking_problem',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
