# Generated by Django 5.1.4 on 2025-04-14 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_clinical_record_fasting_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='static_clinical_data',
            old_name='stroke',
            new_name='smoke',
        ),
    ]
