# Generated by Django 5.1.4 on 2025-04-20 11:10

import chatbot.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_rename_stroke_static_clinical_data_smoke'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CardiacCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=chatbot.models.patient_directory_path)),
                ('file_type', models.CharField(choices=[('DICOM', 'DICOM (.dcm)'), ('PDF', 'Report (.pdf)'), ('MP4', 'Video (.mp4)'), ('PNG', 'Image (.png)'), ('JPG', 'Image (.jpg)'), ('OTHER', 'Other')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('indication', models.CharField(choices=[('CALCIUM', 'Calcium Scoring'), ('CTA', 'Coronary CTA'), ('ANATOMY', 'Cardiac Anatomy'), ('OTHER', 'Other')], max_length=100)),
                ('radiation_dose', models.FloatField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CardiacMRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=chatbot.models.patient_directory_path)),
                ('file_type', models.CharField(choices=[('DICOM', 'DICOM (.dcm)'), ('PDF', 'Report (.pdf)'), ('MP4', 'Video (.mp4)'), ('PNG', 'Image (.png)'), ('JPG', 'Image (.jpg)'), ('OTHER', 'Other')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('sequence_type', models.CharField(choices=[('LGE', 'Late Gadolinium Enhancement'), ('CINE', 'Cine MRI'), ('T1', 'T1 Mapping'), ('T2', 'T2 Mapping'), ('OTHER', 'Other')], max_length=50)),
                ('slice_thickness', models.FloatField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EchoImaging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to=chatbot.models.patient_directory_path)),
                ('file_type', models.CharField(choices=[('DICOM', 'DICOM (.dcm)'), ('PDF', 'Report (.pdf)'), ('MP4', 'Video (.mp4)'), ('PNG', 'Image (.png)'), ('JPG', 'Image (.jpg)'), ('OTHER', 'Other')], max_length=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('view_type', models.CharField(choices=[('PLAX', 'Parasternal Long Axis'), ('A4C', 'Apical 4 Chamber'), ('PSAX', 'Parasternal Short Axis'), ('SUBC', 'Subcostal'), ('OTHER', 'Other')], max_length=50)),
                ('ejection_fraction', models.FloatField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
