# Generated by Django 5.1.4 on 2025-05-01 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0005_cardiacct_cardiacmri_echoimaging'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clinical_record',
            old_name='Fasting',
            new_name='chest_pain',
        ),
        migrations.AddField(
            model_name='clinical_record',
            name='fasting',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
