# Generated by Django 5.1.4 on 2025-05-12 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0006_rename_fasting_clinical_record_chest_pain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardiacct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cardiacmri',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='echoimaging',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
