# Generated by Django 5.1.4 on 2025-05-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_cardiacct_created_at_cardiacmri_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardiacct',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cardiacmri',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='echoimaging',
            name='created_at',
        ),
    ]
