# Generated by Django 5.1.4 on 2025-12-03 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0008_remove_cardiacct_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='state',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
