# Generated by Django 5.1.4 on 2025-12-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0009_conversation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='tread_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
