# Generated by Django 5.1.4 on 2025-12-03 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_conversation_tread_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='tread_id',
            new_name='thread_id',
        ),
    ]
