# Generated by Django 5.1.4 on 2025-12-06 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_rename_tread_id_conversation_thread_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
