# Generated by Django 5.1.4 on 2025-04-14 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_patient_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
